version: '3'
services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./code:/app
      - ./dags:/app/airflow/dags
      - ./logs:/app/airflow/logs
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
